---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 80}]
        - ["private_network", { ip: "192.168.7.7"}]

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret" 
    run_list:
      - recipe[docker-demo::default]
    attributes:
