name 'docker-demo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures docker-demo'
long_description 'Installs/Configures docker-demo'
version '0.1.0'
depends 'docker', '~> 2.0'
